import { ChangeEvent, useRef, useState } from 'react'
import { ArrowLeft, Camera, CheckCircle2, FileText, Paperclip, Play, ShieldCheck, UploadCloud, X } from 'lucide-react'
import { useNav } from '../context/NavContext'
import { StatusBar } from '../components/shared'

type Attachment = { id: string; file: File; kind: 'image' | 'video' | 'file'; url?: string }

const getKind = (file: File): Attachment['kind'] => file.type.startsWith('image/') ? 'image' : file.type.startsWith('video/') ? 'video' : 'file'
const formatSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`

export default function CompletionEvidencePage() {
  const { goBack, navigate, params } = useNav()
  const booking = params || { name: 'Sara Al Mannai', service: 'Deep Cleaning', location: 'Al Sadd, Doha', time: '09:00 AM', av: 'S', price: '280.00' }
  const inputRef = useRef<HTMLInputElement>(null)
  const [attachments, setAttachments] = useState<Attachment[]>([])
  const [notes, setNotes] = useState('')
  const [submitted, setSubmitted] = useState(false)

  const addFiles = (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || [])
    const next = files.map(file => ({ id: `${file.name}-${file.lastModified}-${Math.random()}`, file, kind: getKind(file), url: file.type.startsWith('image/') || file.type.startsWith('video/') ? URL.createObjectURL(file) : undefined }))
    setAttachments(current => [...current, ...next].slice(0, 8))
    event.target.value = ''
  }
  const removeFile = (attachment: Attachment) => {
    if (attachment.url) URL.revokeObjectURL(attachment.url)
    setAttachments(current => current.filter(item => item.id !== attachment.id))
  }
  const canSubmit = attachments.length > 0 || notes.trim().length > 0

  if (submitted) return <div className="flex flex-col flex-1 bg-[#F4F6FF] overflow-hidden"><StatusBar /><div className="flex-1 overflow-y-auto px-5 flex flex-col items-center justify-center pb-10"><div className="w-20 h-20 rounded-full bg-green-100 flex items-center justify-center mb-5"><CheckCircle2 size={42} className="text-green-500" /></div><h1 className="text-[23px] font-bold text-gray-900 text-center">Job marked complete</h1><p className="text-[13px] text-gray-500 text-center leading-relaxed mt-2 max-w-[285px]">Your completion update has been sent to {booking.name}. They can now view the work you shared.</p><div className="w-full bg-white rounded-2xl shadow-sm p-4 mt-7 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-blue-50 flex items-center justify-center"><Paperclip size={19} className="text-brand-500" /></div><div className="flex-1"><p className="text-[13px] font-bold text-gray-800">Completion evidence shared</p><p className="text-[11px] text-gray-400">{attachments.length} attachment{attachments.length === 1 ? '' : 's'}{notes.trim() ? ' and a job note' : ''}</p></div><CheckCircle2 size={19} className="text-green-500" /></div><div className="w-full bg-amber-50 rounded-2xl p-4 mt-3 flex gap-3"><ShieldCheck size={19} className="text-amber-500 shrink-0 mt-0.5" /><p className="text-[12px] text-amber-700 leading-relaxed">The payment will be released according to Helpy’s completion policy.</p></div><button onClick={() => navigate('booking-detail', { ...booking, status: 'Completed', avatar: booking.av || booking.name?.[0] })} className="w-full mt-7 py-3.5 rounded-2xl bg-brand-500 text-white text-[14px] font-bold">View completed booking</button><button onClick={goBack} className="mt-4 text-[13px] font-semibold text-gray-500">Back to in-progress jobs</button></div></div>

  return <div className="flex flex-col flex-1 bg-[#F4F6FF] overflow-hidden"><StatusBar /><div className="flex items-center gap-3 px-4 pt-2 pb-3 bg-[#F4F6FF]"><button onClick={goBack} className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center"><ArrowLeft size={20} className="text-gray-600" /></button><div className="min-w-0"><h1 className="text-[18px] font-bold text-gray-900">Complete service</h1><p className="text-[11px] text-gray-400 truncate">Share the finished work with {booking.name}</p></div></div><div className="flex-1 overflow-y-auto px-4 pb-6 space-y-4"><div className="bg-brand-500 rounded-2xl p-4 text-white relative overflow-hidden"><div className="absolute -right-6 -top-6 w-24 h-24 rounded-full bg-white/10" /><div className="relative flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-white/15 flex items-center justify-center shrink-0"><Camera size={19} /></div><div><p className="text-[14px] font-bold">Show the work you completed</p><p className="text-[12px] text-white/80 leading-relaxed mt-1">Add photos, videos, or project files so your customer can review the completed service.</p></div></div></div>
    <div className="bg-white rounded-2xl shadow-sm p-4"><div className="flex items-center justify-between mb-3"><div><p className="text-[14px] font-bold text-gray-900">Completion evidence</p><p className="text-[11px] text-gray-400 mt-0.5">Photos, videos, PDFs, or supporting files</p></div><span className="text-[11px] font-semibold text-brand-500">{attachments.length}/8</span></div><input ref={inputRef} onChange={addFiles} type="file" multiple accept="image/*,video/*,.pdf,.doc,.docx,.xlsx" className="hidden" /><button onClick={() => inputRef.current?.click()} className="w-full min-h-28 rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/50 flex flex-col items-center justify-center text-center px-4"><div className="w-10 h-10 rounded-xl bg-white shadow-sm flex items-center justify-center"><UploadCloud size={20} className="text-brand-500" /></div><p className="text-[13px] font-bold text-gray-800 mt-2">Upload completed work</p><p className="text-[11px] text-gray-400 mt-0.5">Select photos, videos, or project files</p></button>{attachments.length > 0 && <div className="grid grid-cols-2 gap-3 mt-4">{attachments.map(attachment => <div key={attachment.id} className="relative rounded-xl border border-gray-100 overflow-hidden bg-gray-50">{attachment.kind === 'image' && attachment.url ? <img src={attachment.url} alt={attachment.file.name} className="w-full h-24 object-cover" /> : attachment.kind === 'video' && attachment.url ? <div className="relative h-24 bg-slate-800"><video src={attachment.url} className="w-full h-full object-cover" /><div className="absolute inset-0 flex items-center justify-center"><span className="w-8 h-8 bg-white/90 rounded-full flex items-center justify-center"><Play size={14} className="text-brand-500 fill-brand-500 ml-0.5" /></span></div></div> : <div className="h-24 flex flex-col items-center justify-center bg-blue-50"><FileText size={27} className="text-brand-500" /><span className="text-[10px] text-gray-400 mt-1">Document</span></div>}<button onClick={() => removeFile(attachment)} className="absolute top-1.5 right-1.5 w-6 h-6 rounded-full bg-gray-900/65 text-white flex items-center justify-center"><X size={13} /></button><div className="px-2.5 py-2 bg-white"><p className="text-[11px] font-semibold text-gray-700 truncate">{attachment.file.name}</p><p className="text-[10px] text-gray-400 mt-0.5">{formatSize(attachment.file.size)}</p></div></div>)}</div>}</div>
    <div className="bg-white rounded-2xl shadow-sm p-4"><div className="flex items-center gap-2"><FileText size={16} className="text-brand-500" /><p className="text-[14px] font-bold text-gray-900">Completion note <span className="font-normal text-gray-400">(optional)</span></p></div><textarea value={notes} onChange={event => setNotes(event.target.value)} maxLength={400} placeholder="Tell the customer what was completed, any areas to note, or follow-up recommendations." className="mt-3 w-full min-h-24 rounded-xl bg-gray-50 border border-transparent focus:border-blue-200 focus:bg-white outline-none p-3 text-[13px] text-gray-700 placeholder:text-gray-400 resize-none" /><p className="text-right text-[10px] text-gray-400 mt-1">{notes.length}/400</p></div>
    <div className="bg-green-50 rounded-2xl p-4 flex gap-3"><ShieldCheck size={19} className="text-green-500 shrink-0 mt-0.5" /><div><p className="text-[12px] font-bold text-green-700">Ready for customer review</p><p className="text-[11px] text-green-600 leading-relaxed mt-0.5">Once submitted, this service will be marked completed and your evidence will be visible to the customer.</p></div></div><button disabled={!canSubmit} onClick={() => setSubmitted(true)} className="w-full py-4 rounded-2xl bg-green-500 disabled:bg-gray-200 disabled:text-gray-400 text-white text-[14px] font-bold shadow-sm transition-colors">Submit &amp; mark job completed</button>{!canSubmit && <p className="text-[11px] text-center text-gray-400 -mt-2">Add a file or completion note to continue</p>}</div></div>
}
