import { ArrowLeft, CheckCircle2, Clapperboard, MessageCircle, Video } from 'lucide-react'
import { useNav } from '../context/NavContext'
import { StatusBar } from '../components/shared'

export default function MarketingVideoSentPage() {
  const { goBack, navigate, params } = useNav()
  const request = params || { type: 'Service showcase', details: '' }
  return <div className="flex flex-1 flex-col overflow-y-auto bg-[#F4F6FF]"><StatusBar /><div className="flex items-center gap-3 px-4 pt-2 pb-3"><button onClick={goBack} className="flex h-10 w-10 items-center justify-center rounded-xl bg-white shadow-sm"><ArrowLeft size={20} className="text-gray-600" /></button><h1 className="text-[18px] font-bold text-gray-900">Request sent</h1></div><div className="flex flex-1 flex-col items-center px-5 pb-10 pt-8 text-center"><div className="relative flex h-24 w-24 items-center justify-center rounded-full bg-green-100"><CheckCircle2 size={48} className="text-green-500" /><div className="absolute -right-1 -top-1 flex h-9 w-9 items-center justify-center rounded-xl bg-violet-100"><Video size={18} className="text-violet-600" /></div></div><h2 className="mt-6 text-[24px] font-bold text-gray-900">Your request is on its way</h2><p className="mt-2 max-w-[300px] text-[13px] leading-relaxed text-gray-500">Our marketing team has received your brief and will contact you with the next steps.</p><div className="mt-7 w-full rounded-3xl bg-white p-4 text-left shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-50"><Clapperboard size={19} className="text-violet-600" /></div><div><p className="text-[13px] font-bold text-gray-900">{request.type}</p><p className="mt-0.5 text-[11px] text-gray-400">Marketing video request · Pending review</p></div></div><div className="mt-4 rounded-2xl bg-gray-50 p-3"><p className="text-[11px] font-semibold text-gray-500">Your brief</p><p className="mt-1 text-[12px] leading-relaxed text-gray-600">{request.details}</p></div></div><div className="mt-4 flex w-full gap-3"><button onClick={() => navigate('chat', { name: 'Helpy Marketing Team', service: 'Video request' })} className="flex-1 flex items-center justify-center gap-2 rounded-2xl bg-white py-3.5 text-[13px] font-bold text-gray-700 shadow-sm"><MessageCircle size={16} /> Message team</button><button onClick={() => navigate('offers')} className="flex-1 rounded-2xl bg-brand-500 py-3.5 text-[13px] font-bold text-white shadow-sm">Back to offers</button></div></div></div>
}
