import { ArrowLeft, MapPin, Phone, MessageCircle, CheckCircle2, Navigation, Camera, Circle } from 'lucide-react'
import { useNav } from '../context/NavContext'
import { StatusBar } from '../components/shared'

const STEPS = ['Booking Confirmed', 'On the Way', 'Arrived at Location', 'Service In Progress', 'Upload proof']
const TIMES = ['9:00 AM', '9:45 AM', '10:05 AM', '10:10 AM']

export default function OngoingServicePage() {
  const { goBack, navigate, params, bookingUpdates, updateBooking } = useNav()
  const b = params || { id: 5, name: 'Sara Al Mannai', service: 'Deep Cleaning', location: 'Al Sadd, Doha', time: '09:00 AM', av: 'S', price: '280.00', progress: -1 }
  const progress = b.id ? bookingUpdates[b.id]?.progress ?? b.progress ?? -1 : b.progress ?? -1
  const updateStage = (index: number) => { if (index === 4) navigate('completion-evidence', b); else if (b.id) updateBooking(b.id, { progress: index }) }

  return <div className="flex flex-col flex-1 bg-[#F4F6FF] overflow-y-auto"><StatusBar />
    <div className="flex items-center gap-3 px-4 pt-2 pb-3"><button onClick={goBack} className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center"><ArrowLeft size={20} className="text-gray-600" /></button><div><h1 className="text-[18px] font-bold text-gray-900">Job In Progress</h1><p className="text-[11px] text-green-500 font-semibold">● Live tracking active</p></div></div>
    <div className="flex-1 overflow-visible px-4 pb-6 space-y-4"><div className="bg-white rounded-2xl shadow-sm p-4 flex items-center gap-4"><div className="w-14 h-14 rounded-full bg-sky-400 flex items-center justify-center text-white text-xl font-bold">{b.av || b.name?.[0]}</div><div className="flex-1"><p className="text-[16px] font-bold text-gray-900">{b.name}</p><p className="text-[13px] text-brand-500 font-semibold">{b.service}</p><div className="flex items-center gap-1 mt-1"><MapPin size={12} className="text-gray-400" /><span className="text-[11px] text-gray-500">{b.location}</span></div></div><span className="bg-amber-100 text-amber-600 text-[11px] font-bold px-3 py-1 rounded-full">In Progress</span></div>
      <div className="bg-white rounded-2xl shadow-sm overflow-hidden h-36"><div className="w-full h-full bg-gradient-to-br from-blue-50 to-blue-100 flex flex-col items-center justify-center gap-1.5 relative"><div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'repeating-linear-gradient(0deg,#3B5BF6 0,#3B5BF6 1px,transparent 1px,transparent 40px),repeating-linear-gradient(90deg,#3B5BF6 0,#3B5BF6 1px,transparent 1px,transparent 40px)' }} /><Navigation size={28} className="text-brand-500" /><p className="text-[13px] font-bold text-brand-500">Live Location Active</p><p className="text-[11px] text-gray-400">{b.location}</p><div className="absolute bottom-3 right-3 bg-white rounded-xl px-3 py-1.5 shadow-sm flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" /><span className="text-[11px] font-semibold text-gray-700">On-site</span></div></div></div>
      <div className="bg-white rounded-2xl shadow-sm p-5"><div className="flex items-center justify-between mb-4"><div><p className="text-[15px] font-bold text-gray-900">Service Progress</p><p className="text-[11px] text-gray-400 mt-0.5">Update each milestone as the work progresses</p></div><span className="text-[11px] font-semibold text-brand-500">{Math.min(progress + 1, 4)} of 4</span></div><div>{STEPS.map((label, index) => { const complete = index <= progress && index < 4; const next = index === progress + 1; const isUpload = index === 4; return <div key={label} className="flex items-start gap-3 mb-4 last:mb-0"><div className="flex flex-col items-center"><div className={`w-8 h-8 rounded-full flex items-center justify-center ${complete ? 'bg-brand-500' : next ? 'bg-blue-50 border-2 border-brand-500' : 'bg-gray-100'}`}>{complete ? <CheckCircle2 size={16} className="text-white" /> : isUpload ? <Camera size={14} className={next ? 'text-brand-500' : 'text-gray-300'} /> : <Circle size={13} className={next ? 'text-brand-500 fill-brand-500' : 'text-gray-300'} />}</div>{index < STEPS.length - 1 && <div className={`w-0.5 h-9 mt-1 ${index < progress ? 'bg-brand-500' : 'bg-gray-200'}`} />}</div><div className="flex-1 pt-1 min-w-0"><p className={`text-[13px] font-semibold ${complete ? 'text-gray-900' : next ? 'text-gray-900' : 'text-gray-400'}`}>{label}</p><p className="text-[11px] text-gray-400 mt-0.5">{complete ? TIMES[index] : next ? 'Waiting for vendor update' : 'Pending'}</p></div>{next && <button onClick={() => updateStage(index)} className={`shrink-0 px-3 py-1.5 rounded-lg text-[11px] font-bold ${isUpload ? 'bg-green-500 text-white' : 'bg-brand-500 text-white'}`}>{isUpload ? 'Upload' : 'Update'}</button>}</div>})}</div></div>
      <div className="bg-blue-50 rounded-2xl p-4 flex gap-3"><CheckCircle2 size={19} className="text-brand-500 shrink-0 mt-0.5" /><div><p className="text-[12px] font-bold text-gray-800">Keep your customer informed</p><p className="text-[11px] text-gray-500 leading-relaxed mt-0.5">Each update is shared with the customer instantly. Upload proof once the service has been completed.</p></div></div>
      <div className="flex gap-3"><button onClick={() => navigate('chat', b)} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl bg-white shadow-sm text-gray-700 text-[13px] font-semibold"><MessageCircle size={16} />Message</button><button className="flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl bg-white shadow-sm text-gray-700 text-[13px] font-semibold"><Phone size={16} />Call Client</button></div>
    </div>
  </div>
}
